# Configuration fol BetterVillager plugin
Enable: true # Disable the plugin functionality, the plugin will no longer add the "trades" to the villagers
# You can only disable / enable the plugin functionality in the config.yml file, so take notice of that